### PR TITLE
Release Proposal: working on v0.9.x

### PR DESCRIPTION
**Pull request by yorkie**
Hello @Rokid/nodejs, Let's working on ShadowNode v0.9 now!

In _v0.8.x_, we have 53 commits pushed, 36 Pull Request merged and 30 issues closed. Let's see what changes we have done.

#### JerryScript

- Add `Function.prototype.name` with _FEATURE_FUNCTION_NAME_ #123.
- Add native function `jerry_has_property_by_index()` #139.
- Add CPU Profiler with _FEATURE_CPU_PROFILER_ which supports to generate flamegraph #176.
- Promise: remove native and use the pure javascript implementation #215.
- Record magic string id for builtin objects and routines #160.
- Use tmpfile() for parser dump storage instead a normal file #178.
- Fix uninitialized memory malloced #165.
- Fix test and build warnings #170 #206.

#### Build
  
- Update upstream travis script #157.
- Remove jsdriver and use new Python-based test driver from upstream #208.
- Run lint before starting test #168.
- Add deploy stage in TravisCI for releases #224.
- Migrate the Node.js core benchmark framework into ShadowNode #134.
- A new tool to see which ECMAScript features are supported #212.
- Add [Codacy](https://www.codacy.com/) for source code scan statically.

#### Bootstrap

- Fix the `Math.random()` by generating different seed with `srand()` #138.
- Add `handlewrap_queue` for clean the handlewrap up more clean #144, #164.
- Improve CLI options, more like Node.js #193.

#### Modules

- Buffer
  - Add `writeInt32LE()` #163.
  - Add `writeInt16LE()` #169.
- Process
  - Proper message display for dlopen function #131.
  - Add `process.title` #225.
- Console
  - Optimize the performance for single params #140.
  - Disable stdio buffering which follows Node.js #182.
- Child Process
  - Use `uv_write` to instead of `uv_try_write` to fix EAGAIN with large buffer #223.
  - Leak: destroy the iotjs_args_t object when process exits #203.
  - Leak: free the blocks by strdup() #198.
- Stream
  - Add encoding parameter for `writable#write` #184.
- Net / TLS
  - Use IPv4 as the default DNS family #135.
  - Fix checking for `shundown()` #154.
  - Inherit TLS socket from `net.Socket` #149.
- HTTP / HTTPS
  - Support chunked transfer encoding and by default #174.
  - Set `Content-Length` by body if not set #142.
  - Allow zero value for `Content-Length` #158.
- D-Bus
  - Support multiple arguments for signal events #205.
  - Improve the error message if the caller is invalid #214.
  - Leak: release leaked allocated string and value #226.
- MQTT
  - Remove unused member and spaces #191.

#### Community

- [shadow-node/ffi](https://github.com/shadow-node/ffi): Add-on for loading and calling dynamic library with pure JavaScript.
- a new committer @LanFly.

In _v0.9_, we will focus on:

- Implement the 80% N-API with the following rules:
  - `node.h` must be pulled from Node.js.
  - support backward compatible with the JerryScript modules still.
- Bench: cover and improve the performance `EventEmitter` and other core modules.

### CODE REVIEW

**Comment by algebrait** [comment]
Would you please pend #160 ?
I have found some problem while running deps/jerry/test/jerry-test-suites.
ICE: Assertion 'builtin_id ==ECMA_BUILTIN_ID_DATE_PROTOTYPE || builtin_id == ECMA_BUILTIN_ID_MATH' failed at deps/jerry/jerry-core/ecma/builtin-objects/ecma-builtins.c(ecma_builtin_try_to_instantiate_property):793.
I'll try to fix it. If one day is not enough, I suggest to revert it in release version.

**Comment by yorkie** [comment]
> I'll try to fix it. If one day is not enough, I suggest to revert it in release version.

Never mind, will revert it if this won't got fixed today.

**Comment by algebrait** [comment]
#233 will fix #160 's crash

**Comment by yorkie** [comment]
> #233 will fix #160 's crash

@algebrait do we have any example JS to reproduce this crash? I use the following that might works:

```js
var a = new Uint8Array(3);
console.log(a.name, Uint8Array.name);
```

**Comment by algebrait** [comment]
>@algebrait do we have any example JS to reproduce this crash? I use the following that might works:
Below is fail list:
jerry-test-suite/es2015/22/22.02/22.02.03/22.02.03-012.js
jerry-test-suite/es2015/22/22.02/22.02.03/22.02.03-007.js
jerry-test-suite/es2015/22/22.02/22.02.03/22.02.03-014.js
jerry-test-suite/es2015/22/22.02/22.02.03/22.02.03-020.js
jerry-test-suite/es2015/22/22.02/22.02.03/22.02.03-010.js
jerry-test-suite/es2015/22/22.02/22.02.03/22.02.03-009.js
jerry-test-suite/es2015/22/22.02/22.02.03/22.02.03-021.js
jerry-test-suite/es2015/22/22.02/22.02.03/22.02.03-018.js
jerry-test-suite/es2015/22/22.02/22.02.03/22.02.03-015.js
jerry-test-suite/es2015/22/22.02/22.02.03/22.02.03-019.js
jerry-test-suite/es2015/22/22.02/22.02.03/22.02.03-017.js
jerry-test-suite/es2015/22/22.02/22.02.03/22.02.03-011.js
jerry-test-suite/es2015/22/22.02/22.02.03/22.02.03-008.js
jerry-test-suite/es2015/22/22.02/22.02.03/22.02.03-016.js
jerry-test-suite/es2015/22/22.02/22.02.03/22.02.03-013.js
jerry-test-suite/es2015/24/24.01/24.01.04/24.01.04-004.js
jerry-test-suite/es2015/24/24.01/24.01.04/24.01.04-006.js
jerry-test-suite/es2015/24/24.01/24.01.04/24.01.04-005.js
jerry-test-suite/es2015/24/24.01/24.01.04/24.01.04-007.js

I am trying to pass ./tools/run-tests.py --jerry-test-suite under deps/jerry
, but it rans all profiles, and some cases failed because es2015 features are in macros. Fixing them is a little boring, so I would fix them later. And now, they pass all in normal build. So I think it is not a block issue for Shadow-Node 0.9.0.

**Comment by algebrait** [comment]
>I am trying to pass ./tools/run-tests.py --jerry-test-suite under deps/jerry
, but it rans all profiles, and some cases failed because es2015 features are in macros. Fixing them is a little boring, so I would fix them later. And now, they pass all in normal build. So I think it is not a block issue for Shadow-Node 0.9.0.

This issue is tracked by #234 .

**Comment by yorkie** [comment]
Rebased with 09b52a4bfccfcd7df9c4414af5bfe83559099b50 and 48b854656d59da4493a2aa11e5a7ed532c8cac96.

**Pull request merged**
