### PR TITLE
[WIP] add a simple cpu profiler to generate flamegraph

### PR DESCRIPTION
**Pull request by algebrait**
work in progress, do not merge

### CODE REVIEW

**Comment by algebrait** [comment]
usage:

`var profiler = require('profiler');
profiler.startProfiling(path/*optional*/, duration/*optional*/);
profiler.stopProfiling`

iotjs will generate a profiler file (path or Profile-${Date.now()), and a debug info file iotjs.dump.
run
`tools/profiler/cl.py path iotjs.dump > YOUR_COLLAPSEFILE`
to generate collapsed file, then
`tools/profiler/flamegraph.py YOUR_COLLAPSEFILE > YOUR_HTML'
to generate html flame graph file.

**Comment by yorkie** [comment]
@algebrait Could you please create a branch under Rokid/ShadowNode such that I can modify the source code as well?

**Comment by algebrait** [comment]
https://github.com/Rokid/ShadowNode/tree/cpu-profiler

**Comment by yorkie** [comment]
Thanks, now I'm closing this one.

**Pull request closed without merging**
