### PR TITLE
assert: Build assert deep strict equal

### PR DESCRIPTION
**Pull request by Txiaozhe**
##### Checklist

- [x] `npm test` passes
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added

### CODE REVIEW

**Comment by Txiaozhe** [comment]
After this pr merged, I will redo #420 , thanks! :)

**Comment by yorkie** [comment]
Still too many commits :(

**Comment by yorkie** [comment]
@Txiaozhe You could try the following:

```shell
$ git checkout master
$ git pull origin master
$ git checkout -b new/assert
$ git cherry-pick {your_commit_id}
```

**Comment by Txiaozhe** [comment]
> @Txiaozhe You could try the following:
> 
> ```shell
> $ git checkout master
> $ git pull origin master
> $ git checkout -b new/assert
> $ git cherry-pick {your_commit_id}
> ```

Thanks! This is a handy and effective way.

**Pull request closed without merging**
