### PR TITLE
process: set immediate shall start an idle handle to activate uv_loop

### PR DESCRIPTION
**Pull request by legendecas**
- [x] `npm test` passes

### CODE REVIEW

**Comment by yorkie** [comment]
Good nice, LGTM if CI is green 👍

**Comment by yorkie** [comment]
The CI seems fail(timeout) at `TIMEOUT: napi_reference.test.js`.

**Comment by legendecas** [comment]
@yorkie setImmediate has been refactored so that uv loop could not be blocked on polling if there is only check handles.

**Comment by yorkie** [comment]
Because this depends on #406, labeled as `minor` as well.

**Pull request merged**
