### PR TITLE
process: add signal events support

### PR DESCRIPTION
**Pull request by yorkie**
##### Checklist

- [x] `npm test` passes
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added

Added the signal events support by Node.js API, and this is mainly the precondition of simplifying the progress of taking the snapshot, and other debugger/dump usages.

/cc @lolBig @legendecas @fighterkin @algebrait

### CODE REVIEW

**Comment by legendecas** [comment]
Does invocation of `process.exit` in signal listeners work immediately if a timer still waiting?

**Comment by yorkie** [comment]
The Node.js documentation about `process.exit`:

> Calling `process.exit()` will force the process to exit as quickly as possible even if there are still asynchronous operations pending that have not yet completed fully, including I/O operations to process.stdout and process.stderr.

So the answer should be yes, `process.exit()` exits the current process immediately.

**Comment by yorkie** [comment]
@legendecas Added an issue #373 about the current wrong at `process.exit()`, and we will address that in another patch.

**Comment by lolBig** [comment]
LGTM

**Pull request merged**
