### PR TITLE
child_process: free blocks from strdup() which causes memory leaks

### PR DESCRIPTION
**Pull request by yorkie**
This is going to fix almost #195, the memory leaks from `child_process`. This shows the data list of the leaks:

| codebase | rss(from) | rss(to) | leaked bytes |
|-----------|----------|--------|--------------|
|  [master](https://github.com/Rokid/ShadowNode/tree/master)     | 2654208 | 3555328 | 901120 |
| [fix/gh-195](https://github.com/Rokid/ShadowNode/tree/fix/gh-195) | 2576384 | 3002368 | 425984 |

Added a memory test script as well, someone could run by:

```sh
$ iotjs test/memory/child_process.js
Memory Leak Summary(389 samples):
 Rss(From): 2654208
 Rss(End ): 3555328
 Detects 901120 bytes
```

@legendecas @lolBig Needs your reviews on this PR.

### CODE REVIEW

**Comment by lolBig** [comment]
zhe sudu, niubi niubi

**Comment by legendecas** [comment]
Nice, leaks have been fixed👍

**Comment by yorkie** [comment]
But I still found some weird increasing RSS stub, here is a log example:

```
> total: 2785280, increase: 0
> total: 2785280, increase: 0
> total: 2785280, increase: 0
> total: 2785280, increase: 0
> total: 2785280, increase: 0
> total: 2785280, increase: 0
> total: 2785280, increase: 0
> total: 2785280, increase: 0
> total: 2785280, increase: 0
> total: 2785280, increase: 0
> total: 2785280, increase: 0
> total: 2850816, increase: 65536
> total: 2850816, increase: 0
> total: 2850816, increase: 0
> total: 2850816, increase: 0
> total: 2850816, increase: 0
> total: 2850816, increase: 0
> total: 2854912, increase: 4096
> total: 2854912, increase: 0
> total: 2854912, increase: 0
> total: 2854912, increase: 0
> total: 2854912, increase: 0
> total: 2854912, increase: 0
> total: 2854912, increase: 0
> total: 2854912, increase: 0
> total: 2854912, increase: 0
> total: 2854912, increase: 0
> total: 2854912, increase: 0
> total: 2854912, increase: 0
> total: 2854912, increase: 0
> total: 2854912, increase: 0
> total: 2854912, increase: 0
> total: 2854912, increase: 0
> total: 2854912, increase: 0
> total: 2854912, increase: 0
> total: 2854912, increase: 0
> total: 2854912, increase: 0
> total: 2854912, increase: 0
> total: 2854912, increase: 0
> total: 2863104, increase: 8192
> total: 2863104, increase: 0
> total: 2863104, increase: 0
> total: 2863104, increase: 0
> total: 2863104, increase: 0
> total: 2863104, increase: 0
> total: 2863104, increase: 0
> total: 2863104, increase: 0
> total: 2863104, increase: 0
> total: 2863104, increase: 0
> total: 2863104, increase: 0
> total: 2863104, increase: 0
> total: 2863104, increase: 0
> total: 2863104, increase: 0
> total: 2928640, increase: 65536
```

That's different from previous case, it increases 65536 bytes.

**Comment by lolBig** [comment]
why does the leaks increased with 2^n bytes every time? it looks strangly

**Comment by yorkie** [comment]
> why does the leaks increased with 2^n bytes every time? it looks strangly

That shows the sizes of malloc-ing are in alignment and valid :p

**Comment by lolBig** [comment]
啥意思

**Comment by yorkie** [comment]
就是说我们在分配内存的时候，都是按照2的N次方分配的，所以泄漏当然也是这个数值的，这个我觉得没什么问题哦。

**Comment by yorkie** [comment]
The latest output is:

```
:: 2318336 + 81920 bytes
:: 2437120 + 118784 bytes
:: 2449408 + 12288 bytes
:: 2592768 + 143360 bytes
:: 2596864 + 4096 bytes
:: 2600960 + 4096 bytes
:: 2686976 + 86016 bytes
:: 2756608 + 69632 bytes
:: 2760704 + 4096 bytes
:: 2768896 + 8192 bytes
:: 2850816 + 81920 bytes
:: 2859008 + 8192 bytes
:: 2867200 + 8192 bytes
:: 2871296 + 4096 bytes
:: 2875392 + 4096 bytes
:: 2879488 + 4096 bytes
:: 2945024 + 65536 bytes
:: 3010560 + 65536 bytes
:: 3014656 + 4096 bytes
:: 3018752 + 4096 bytes
:: 3022848 + 4096 bytes
:: 3026944 + 4096 bytes
:: 3035136 + 8192 bytes
:: 3039232 + 4096 bytes
:: 3043328 + 4096 bytes
:: 3051520 + 8192 bytes

Memory Summary(429 samples):
 Duration 7s
 Rss(From): 2850816
 Rss(End): 3051520
 Heap(From): 137992
 Heap(End): 175464
 Detects 200704 bytes in total
 Detects 37472 bytes in vm heap
====================================================
 Increasing Count  : 15 / 429
 Decreasing Count  : 0 / 429
 Increasing Rate   : 3%
 Decreasing Rate   : 0%
```
Memory leaks still exits, but let's merge this now if CI is green.

**Pull request merged**
